# Generated by Django 3.1.6 on 2021-02-16 05:04

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favour_book', models.CharField(max_length=30)),
                ('favour_movie', models.TextField(max_length=30)),
                ('language', django_countries.fields.CountryField(max_length=2)),
                ('preference', models.CharField(choices=[('movie', 'Movie'), ('books', 'Book')], max_length=20)),
                ('bio', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
            ],
        ),
    ]
